version: 2.1

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:19.7.0-browsers

jobs:
  validate:
    executor: pnpm-executor
    steps:
      - checkout
      - run:
          name: Install packages
          command: pnpm install
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Validate
          command: pnpm run validate

workflows:
  flow:
    jobs:
      - validate

